// AUTO-GENERATED by scripts/sync-chapters.mjs — DO NOT EDIT MANUALLY.
// Drop chN.json into frontend/public/data/books/ and run npm run dev or npm run build.
import type { Topic } from './topics';

export const bookChapters: Topic[] = [
  { id: 'book-ch1', name: 'Chapter 1: Basic Electrical & Electronics', shortName: 'Ch1 - Basic Electrical & Electronics', description: 'Ohm\'s Law, circuit analysis, AC/DC circuits and electronic components', questionCount: 587, icon: 'chip' as Topic['icon'], color: '#f59e0b', dataFile: 'books/ch1.json' },
  { id: 'book-ch2', name: 'Chapter 2: Digital Logic & Number Systems', shortName: 'Ch2 - Digital Logic & Number Systems', description: 'Number systems, Boolean algebra, logic gates and digital electronics', questionCount: 746, icon: 'chip' as Topic['icon'], color: '#6366f1', dataFile: 'books/ch2.json' },
  { id: 'book-ch3', name: 'Chapter 3: C / C++ Programming', shortName: 'Ch3 - C / C++ Programming', description: 'C and C++ fundamentals, pointers, data types and OOP concepts', questionCount: 398, icon: 'code' as Topic['icon'], color: '#22c55e', dataFile: 'books/ch3.json' },
  { id: 'book-ch4', name: 'Chapter 4: Operating Systems & DBMS', shortName: 'Ch4 - Operating Systems & DBMS', description: 'OS process management, memory, databases and algorithms', questionCount: 57, icon: 'database' as Topic['icon'], color: '#ec4899', dataFile: 'books/ch4.json' },
  { id: 'book-ch5', name: 'Chapter 5: Computer Networks & Security', shortName: 'Ch5 - Computer Networks & Security', description: 'Network protocols, OSI model and network security concepts', questionCount: 69, icon: 'brain' as Topic['icon'], color: '#06b6d4', dataFile: 'books/ch5.json' },
  { id: 'book-ch6', name: 'Chapter 6', shortName: 'Ch6 - Chapter 6', description: 'Questions from chapter 6 of the engineering exam textbook', questionCount: 64, icon: 'network' as Topic['icon'], color: '#a855f7', dataFile: 'books/ch6.json' },
  { id: 'book-ch7', name: 'Chapter 7: Digital Logic & Number Systems', shortName: 'Ch7 - Digital Logic & Number Systems', description: 'Number systems, Boolean algebra, logic gates and digital electronics', questionCount: 69, icon: 'monitor' as Topic['icon'], color: '#f97316', dataFile: 'books/ch7.json' },
  { id: 'book-ch8', name: 'Chapter 8', shortName: 'Ch8 - Chapter 8', description: 'Questions from chapter 8 of the engineering exam textbook', questionCount: 72, icon: 'calculator' as Topic['icon'], color: '#10b981', dataFile: 'books/ch8.json' },
  { id: 'book-ch9', name: 'Chapter 9: AI & Machine Learning', shortName: 'Ch9 - AI & Machine Learning', description: 'Artificial intelligence, neural networks and machine learning concepts', questionCount: 71, icon: 'book' as Topic['icon'], color: '#3b82f6', dataFile: 'books/ch9.json' },
  { id: 'book-ch10', name: 'Chapter 10', shortName: 'Ch10 - Chapter 10', description: 'Questions from chapter 10 of the engineering exam textbook', questionCount: 70, icon: 'settings' as Topic['icon'], color: '#8b5cf6', dataFile: 'books/ch10.json' },
];
